### ISSUE TITLE
# [1.x] Bump composer dependencies

### ISSUE THREAD

**Issue by imdhemy** [piscibus/siklid-api#261]
### Description

**Acceptance criteria**

- [x] All dependencies are bumped to their latest version
    - [x] upgrade psalm to v5
- [x] The application is still working as expected
- [x] The semantic versions should be in the form `^1.0` not `1.0.*` nor `^1.0.0`. 
- [x] No asterisk should be used nor the patch version.

**Comment by Moemen-Gaballah** [comment]
1- first step mean only running composer dump?

**Comment by Moemen-Gaballah** [comment]
Hello Eng @imdhemy  
can you give me any advice about this task?

After running the composer bump 
and composer update gets an Error as the image.



![Image](https://user-images.githubusercontent.com/31255104/230768492-3941dc94-c0f9-473e-b82d-1d8eb2868f73.png)

**Comment by imdhemy** [comment]
@Moemen-Gaballah Please create a draft PR so that I can help you.
