### ISSUE TITLE
[1.x]  Create Service Container

### ISSUE THREAD

**Issue by mgamal92** [piscibus/siklid-api#278]
### Description
In some cases we need to inject some classes or services like Repositories

### Acceptance Criteria
- [ ] Create container.
- [ ] Inject services with their parameters using ReflectionClass.

### Example

```php
$container = Container::instance(); // singleton instance
$service = $container->get('SomeService');
```

**Comment by imdhemy** [comment]
We already have a container, the Symfony container. 
As per our discussion, we need to use repositories as services to be able to inject them into our actions.
