### ISSUE TITLE
[1.x] Add endpoint for logout

### ISSUE THREAD

**Issue by imdhemy** [piscibus/siklid-api#54]
### Description

As per the title...

**Comment by Moemen-Gaballah** [comment]
I will do it ISA.

**Comment by imdhemy** [comment]
Great! It's assigned to you now! 😉

**Comment by imdhemy** [comment]
Heya @Moemen-Gaballah 

You may encounter an `Invalid credentials' error even with using a valid access token. I'm going to fix this today Inshallah.

**Comment by Moemen-Gaballah** [comment]
@imdhemy 
Good morning
Can you share a postman collection ?

**Comment by imdhemy** [comment]
You can find it here

https://www.postman.com/piscibus/workspace/siklid/collection/1271923-9f6f7d88-bfd4-446c-b2ed-79f4db0d195e?action=share&creator=1271923

**Comment by Moemen-Gaballah** [comment]
@imdhemy 
done store invalid token to cache (file) but when change adapter to redis I think some thing wrong
and I don't know where can add middleware in sympony ? 
I will check it again evening or tomorrow.
