### ISSUE TITLE
[1.x] Add `arrayToJson()` to the `Json` class

### ISSUE THREAD

**Issue by imdhemy** [piscibus/siklid-api#73]
### Description

The `\App\Foundation\Util\Json` has `jsonToArray` which converts JSON into an array safely.

This issue requests adding a new method `arrayToJson()` that should convert an array into JSON safely as well.

**Comment by ramytamer** [comment]
Why do we need an `arrayToJson` method? What would be the difference between it and `json_encode`?

**Comment by imdhemy** [comment]
The default behavior of the `json_encode()` function in case of failure is to throw an `Error`.
As you already know, Errors are not recoverable and will stop the execution of your script.

This is not always the desired behavior, especially when you are dealing with user input. In this case, we might gain
advantage of throwing an exception instead, or even, returning `null` instead of throwing an exception.

This could be done by using `JSON_THROW_ON_ERROR` as the second parameter of the `json_encode()` function.

**Advantages:**

1. You can catch the exception and handle it in a way that is more suitable for your application.
2. No annoying IDEs warnings about uncaught exceptions.
3. Unified behavior across all your code.

What do you think? Is this a good idea? Is there a better way to handle this? Please share your thoughts.

**Comment by Moemen-Gaballah** [comment]
Done ISA add pull request.
